from .asia import asia
from .cmu import cmu
from .csmu import csmu
from .ctust import ctust
from .cyut import cyut
from .fcu import fcu
from .hk import hk
from .hust import hust
from .ltu import ltu
from .nchu import nchu
from .ncut import ncut
from .ntcu import ntcu
from .ntupes import ntupes
from .nutc import nutc
from .ocu import ocu
from .pu import pu
from .thu import thu
