from .csu import csu
from .fotech import fotech
from .fy import fy
from .isu import isu
from .kmu import kmu
from .kyu import kyu
from .nknu import nknu
from .nkuht import nkuht
from .nkust import nkust
from .nsysu import nsysu
from .nuk import nuk
from .stu import stu
from .szmc import szmc
from .tf import tf
from .wzu import wzu
from .yuhing import yuhing
